select  * from customer
limit 20;

--Q1. What is the total revenue generated by the male vs. female customers?

 SELECT 
 gender,
 SUM(sales) as total_sales
 FROM customer
 GROUP BY gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id,sales
from customer
where discount_applied = 'Yes' and sales > (select avg(sales) from customer)

--Q3. Which are the top5 products with the highest average review rating?

select 
item_purchased, 
round(avg(review_rating::numeric),2) as average_review_rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average purchase amounts between standard and express shipping.

select
shipping_type,
round(avg(sales),2)
from customer
where shipping_type in ('Express','Standard')
group by shipping_type

--Q5. Do Subscibed customer spend more? compare average spend and total revenue 
-- between subscribers and non-subscribers

select
subscription_status,
round(sum(sales),2) total_sales,
round(avg(sales),2) avg_sales,
count(customer_id) total_customers
from customer
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchase with discounts applied?

SELECT 
  item_purchased,
  ROUND(100.0 * discounted_count / total_count, 2) AS discount_rate
FROM (
  SELECT 
    item_purchased,
    COUNT(*) AS total_count,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_count
  FROM customer
  GROUP BY item_purchased
) AS summary
ORDER BY discount_rate DESC
LIMIT 5;

--OR

SELECT 
  item_purchased,
  ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Q7. Segment customers into new, returning and loyal based on their total number of 
-- previous purchases and show the count of each segment.

select customer_segment,
count(customer_segment)
from(
select customer_id,
previous_purchases,
case 
	 when previous_purchases= 1 then 'New'
	 when previous_purchases between 1 and 10 then 'Returning'
     else 'Loyal'
	 end as customer_segment
from customer
)
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?

with item_ranked as(
select 
category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select
*
from item_ranked
where item_rank <4

--Q9. Are customers who are repeat buyers(more tha 5 previous purchases) also likely to subscirbe?

select
count(customer_id) total_repeaters,
sum(subscribe) subscribers
from(
select customer_id,
previous_purchases,
subscription_status,
case when subscription_status ='Yes' then 1
else 0 end as subscribe
from customer
where previous_purchases > 5 
)

--OR

select
count(customer_id) customers,
subscription_status
from customer
where previous_purchases > 5 
group by subscription_status

--Q10. What is the revenue contribution of each age group

select 
age_group,
sum(sales) total_sales
from customer
group by age_group
order by total_sales desc
